name: PR Docu Checks

on:
  pull_request:
    branches:
      - "main"
      - "release-*"
    paths-ignore:
      - 'dependencies/**'
      - 'OWNERS'
      - 'CODEOWNERS'
      - 'external-images.yaml'
  workflow_dispatch:

jobs:
  verify-manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: "./.github/template/setup-golang"

      - name: Verify manifests
        run: make crd-docs-gen manifests-dev check-clean

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install md-check-link
        run: npm install -g md-check-link
      - name: Verify links
        run: |
          md-check-link -q -n 8 -c https://raw.githubusercontent.com/kyma-project/md-check-link/main/.mlc.config.json ./

  sync-dita-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out code
        uses: actions/checkout@v4

      - name: Check changes in user docs folder
        uses: tj-actions/changed-files@6b2903bdce6310cfbddd87c418f253cf29b2dec9
        id: changed-docs
        with:
          files: "docs/user/**"

      - name: Add "Sync with DITA" label
        run: |
          if ${{ steps.changed-docs.outputs.any_changed }}; then
           gh pr edit $NUMBER --add-label "sync-with-dita"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}

